// Copyright 2019 Luis Guillén Civera <luisguillenc@gmail.com>. View LICENSE.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.6.1
// source: github.com/luids-io/api/schemas/event/common.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type EventType int32

const (
	EventType_UNDEFINED EventType = 0
	EventType_SECURITY  EventType = 1
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0: "UNDEFINED",
		1: "SECURITY",
	}
	EventType_value = map[string]int32{
		"UNDEFINED": 0,
		"SECURITY":  1,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_github_com_luids_io_api_schemas_event_common_proto_enumTypes[0].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_github_com_luids_io_api_schemas_event_common_proto_enumTypes[0]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_github_com_luids_io_api_schemas_event_common_proto_rawDescGZIP(), []int{0}
}

type EventLevel int32

const (
	EventLevel_INFO     EventLevel = 0
	EventLevel_LOW      EventLevel = 1
	EventLevel_MEDIUM   EventLevel = 2
	EventLevel_HIGH     EventLevel = 3
	EventLevel_CRITICAL EventLevel = 4
)

// Enum value maps for EventLevel.
var (
	EventLevel_name = map[int32]string{
		0: "INFO",
		1: "LOW",
		2: "MEDIUM",
		3: "HIGH",
		4: "CRITICAL",
	}
	EventLevel_value = map[string]int32{
		"INFO":     0,
		"LOW":      1,
		"MEDIUM":   2,
		"HIGH":     3,
		"CRITICAL": 4,
	}
)

func (x EventLevel) Enum() *EventLevel {
	p := new(EventLevel)
	*p = x
	return p
}

func (x EventLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_github_com_luids_io_api_schemas_event_common_proto_enumTypes[1].Descriptor()
}

func (EventLevel) Type() protoreflect.EnumType {
	return &file_github_com_luids_io_api_schemas_event_common_proto_enumTypes[1]
}

func (x EventLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventLevel.Descriptor instead.
func (EventLevel) EnumDescriptor() ([]byte, []int) {
	return file_github_com_luids_io_api_schemas_event_common_proto_rawDescGZIP(), []int{1}
}

type EventData_DataEnc int32

const (
	EventData_NODATA EventData_DataEnc = 0
	EventData_JSON   EventData_DataEnc = 1
)

// Enum value maps for EventData_DataEnc.
var (
	EventData_DataEnc_name = map[int32]string{
		0: "NODATA",
		1: "JSON",
	}
	EventData_DataEnc_value = map[string]int32{
		"NODATA": 0,
		"JSON":   1,
	}
)

func (x EventData_DataEnc) Enum() *EventData_DataEnc {
	p := new(EventData_DataEnc)
	*p = x
	return p
}

func (x EventData_DataEnc) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventData_DataEnc) Descriptor() protoreflect.EnumDescriptor {
	return file_github_com_luids_io_api_schemas_event_common_proto_enumTypes[2].Descriptor()
}

func (EventData_DataEnc) Type() protoreflect.EnumType {
	return &file_github_com_luids_io_api_schemas_event_common_proto_enumTypes[2]
}

func (x EventData_DataEnc) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventData_DataEnc.Descriptor instead.
func (EventData_DataEnc) EnumDescriptor() ([]byte, []int) {
	return file_github_com_luids_io_api_schemas_event_common_proto_rawDescGZIP(), []int{2, 0}
}

type EventSource struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hostname string `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Program  string `protobuf:"bytes,2,opt,name=program,proto3" json:"program,omitempty"`
	Instance string `protobuf:"bytes,3,opt,name=instance,proto3" json:"instance,omitempty"`
	Pid      uint32 `protobuf:"varint,4,opt,name=pid,proto3" json:"pid,omitempty"`
}

func (x *EventSource) Reset() {
	*x = EventSource{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_luids_io_api_schemas_event_common_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventSource) ProtoMessage() {}

func (x *EventSource) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_luids_io_api_schemas_event_common_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventSource.ProtoReflect.Descriptor instead.
func (*EventSource) Descriptor() ([]byte, []int) {
	return file_github_com_luids_io_api_schemas_event_common_proto_rawDescGZIP(), []int{0}
}

func (x *EventSource) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *EventSource) GetProgram() string {
	if x != nil {
		return x.Program
	}
	return ""
}

func (x *EventSource) GetInstance() string {
	if x != nil {
		return x.Instance
	}
	return ""
}

func (x *EventSource) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

type ProcessInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReceivedTs *timestamp.Timestamp `protobuf:"bytes,1,opt,name=received_ts,json=receivedTs,proto3" json:"received_ts,omitempty"`
	Processor  *EventSource         `protobuf:"bytes,2,opt,name=processor,proto3" json:"processor,omitempty"`
}

func (x *ProcessInfo) Reset() {
	*x = ProcessInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_luids_io_api_schemas_event_common_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProcessInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessInfo) ProtoMessage() {}

func (x *ProcessInfo) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_luids_io_api_schemas_event_common_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessInfo.ProtoReflect.Descriptor instead.
func (*ProcessInfo) Descriptor() ([]byte, []int) {
	return file_github_com_luids_io_api_schemas_event_common_proto_rawDescGZIP(), []int{1}
}

func (x *ProcessInfo) GetReceivedTs() *timestamp.Timestamp {
	if x != nil {
		return x.ReceivedTs
	}
	return nil
}

func (x *ProcessInfo) GetProcessor() *EventSource {
	if x != nil {
		return x.Processor
	}
	return nil
}

type EventData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DataEnc EventData_DataEnc `protobuf:"varint,1,opt,name=dataEnc,proto3,enum=luids.event.v1.EventData_DataEnc" json:"dataEnc,omitempty"`
	Data    []byte            `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *EventData) Reset() {
	*x = EventData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_luids_io_api_schemas_event_common_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventData) ProtoMessage() {}

func (x *EventData) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_luids_io_api_schemas_event_common_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventData.ProtoReflect.Descriptor instead.
func (*EventData) Descriptor() ([]byte, []int) {
	return file_github_com_luids_io_api_schemas_event_common_proto_rawDescGZIP(), []int{2}
}

func (x *EventData) GetDataEnc() EventData_DataEnc {
	if x != nil {
		return x.DataEnc
	}
	return EventData_NODATA
}

func (x *EventData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_github_com_luids_io_api_schemas_event_common_proto protoreflect.FileDescriptor

var file_github_com_luids_io_api_schemas_event_common_proto_rawDesc = []byte{
	0x0a, 0x32, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x75, 0x69,
	0x64, 0x73, 0x2d, 0x69, 0x6f, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61,
	0x73, 0x2f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x6c, 0x75, 0x69, 0x64, 0x73, 0x2e, 0x65, 0x76, 0x65, 0x6e,
	0x74, 0x2e, 0x76, 0x31, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x71, 0x0a, 0x0b, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x53, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x6e,
	0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x6e,
	0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x69, 0x64, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x03, 0x70, 0x69, 0x64, 0x22, 0x85, 0x01, 0x0a, 0x0b, 0x50, 0x72, 0x6f,
	0x63, 0x65, 0x73, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x3b, 0x0a, 0x0b, 0x72, 0x65, 0x63, 0x65,
	0x69, 0x76, 0x65, 0x64, 0x5f, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0a, 0x72, 0x65, 0x63, 0x65, 0x69,
	0x76, 0x65, 0x64, 0x54, 0x73, 0x12, 0x39, 0x0a, 0x09, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73,
	0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6c, 0x75, 0x69, 0x64, 0x73,
	0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x53,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72,
	0x22, 0x7d, 0x0a, 0x09, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x3b, 0x0a,
	0x07, 0x64, 0x61, 0x74, 0x61, 0x45, 0x6e, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x21,
	0x2e, 0x6c, 0x75, 0x69, 0x64, 0x73, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x76, 0x31, 0x2e,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x45, 0x6e,
	0x63, 0x52, 0x07, 0x64, 0x61, 0x74, 0x61, 0x45, 0x6e, 0x63, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x1f,
	0x0a, 0x07, 0x44, 0x61, 0x74, 0x61, 0x45, 0x6e, 0x63, 0x12, 0x0a, 0x0a, 0x06, 0x4e, 0x4f, 0x44,
	0x41, 0x54, 0x41, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x4a, 0x53, 0x4f, 0x4e, 0x10, 0x01, 0x2a,
	0x28, 0x0a, 0x09, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0d, 0x0a, 0x09,
	0x55, 0x4e, 0x44, 0x45, 0x46, 0x49, 0x4e, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x53,
	0x45, 0x43, 0x55, 0x52, 0x49, 0x54, 0x59, 0x10, 0x01, 0x2a, 0x43, 0x0a, 0x0a, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x08, 0x0a, 0x04, 0x49, 0x4e, 0x46, 0x4f, 0x10,
	0x00, 0x12, 0x07, 0x0a, 0x03, 0x4c, 0x4f, 0x57, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x4d, 0x45,
	0x44, 0x49, 0x55, 0x4d, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04, 0x48, 0x49, 0x47, 0x48, 0x10, 0x03,
	0x12, 0x0c, 0x0a, 0x08, 0x43, 0x52, 0x49, 0x54, 0x49, 0x43, 0x41, 0x4c, 0x10, 0x04, 0x42, 0x27,
	0x5a, 0x25, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x75, 0x69,
	0x64, 0x73, 0x2d, 0x69, 0x6f, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2f,
	0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_github_com_luids_io_api_schemas_event_common_proto_rawDescOnce sync.Once
	file_github_com_luids_io_api_schemas_event_common_proto_rawDescData = file_github_com_luids_io_api_schemas_event_common_proto_rawDesc
)

func file_github_com_luids_io_api_schemas_event_common_proto_rawDescGZIP() []byte {
	file_github_com_luids_io_api_schemas_event_common_proto_rawDescOnce.Do(func() {
		file_github_com_luids_io_api_schemas_event_common_proto_rawDescData = protoimpl.X.CompressGZIP(file_github_com_luids_io_api_schemas_event_common_proto_rawDescData)
	})
	return file_github_com_luids_io_api_schemas_event_common_proto_rawDescData
}

var file_github_com_luids_io_api_schemas_event_common_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_github_com_luids_io_api_schemas_event_common_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_github_com_luids_io_api_schemas_event_common_proto_goTypes = []interface{}{
	(EventType)(0),              // 0: luids.event.v1.EventType
	(EventLevel)(0),             // 1: luids.event.v1.EventLevel
	(EventData_DataEnc)(0),      // 2: luids.event.v1.EventData.DataEnc
	(*EventSource)(nil),         // 3: luids.event.v1.EventSource
	(*ProcessInfo)(nil),         // 4: luids.event.v1.ProcessInfo
	(*EventData)(nil),           // 5: luids.event.v1.EventData
	(*timestamp.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_github_com_luids_io_api_schemas_event_common_proto_depIdxs = []int32{
	6, // 0: luids.event.v1.ProcessInfo.received_ts:type_name -> google.protobuf.Timestamp
	3, // 1: luids.event.v1.ProcessInfo.processor:type_name -> luids.event.v1.EventSource
	2, // 2: luids.event.v1.EventData.dataEnc:type_name -> luids.event.v1.EventData.DataEnc
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_github_com_luids_io_api_schemas_event_common_proto_init() }
func file_github_com_luids_io_api_schemas_event_common_proto_init() {
	if File_github_com_luids_io_api_schemas_event_common_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_github_com_luids_io_api_schemas_event_common_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventSource); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_luids_io_api_schemas_event_common_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProcessInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_luids_io_api_schemas_event_common_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_github_com_luids_io_api_schemas_event_common_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_luids_io_api_schemas_event_common_proto_goTypes,
		DependencyIndexes: file_github_com_luids_io_api_schemas_event_common_proto_depIdxs,
		EnumInfos:         file_github_com_luids_io_api_schemas_event_common_proto_enumTypes,
		MessageInfos:      file_github_com_luids_io_api_schemas_event_common_proto_msgTypes,
	}.Build()
	File_github_com_luids_io_api_schemas_event_common_proto = out.File
	file_github_com_luids_io_api_schemas_event_common_proto_rawDesc = nil
	file_github_com_luids_io_api_schemas_event_common_proto_goTypes = nil
	file_github_com_luids_io_api_schemas_event_common_proto_depIdxs = nil
}
