// Code generated by protoc-gen-go. DO NOT EDIT.
// source: forward.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ForwardEventRequest struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type                 EventType            `protobuf:"varint,2,opt,name=type,proto3,enum=luids.event.v1.EventType" json:"type,omitempty"`
	Code                 int32                `protobuf:"varint,3,opt,name=code,proto3" json:"code,omitempty"`
	Level                EventLevel           `protobuf:"varint,4,opt,name=level,proto3,enum=luids.event.v1.EventLevel" json:"level,omitempty"`
	CreatedTs            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=created_ts,json=createdTs,proto3" json:"created_ts,omitempty"`
	Source               *EventSource         `protobuf:"bytes,6,opt,name=source,proto3" json:"source,omitempty"`
	Processors           []*ProcessInfo       `protobuf:"bytes,7,rep,name=processors,proto3" json:"processors,omitempty"`
	Data                 *EventData           `protobuf:"bytes,8,opt,name=data,proto3" json:"data,omitempty"`
	Codename             string               `protobuf:"bytes,9,opt,name=codename,proto3" json:"codename,omitempty"`
	Description          string               `protobuf:"bytes,10,opt,name=description,proto3" json:"description,omitempty"`
	Tags                 []string             `protobuf:"bytes,11,rep,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ForwardEventRequest) Reset()         { *m = ForwardEventRequest{} }
func (m *ForwardEventRequest) String() string { return proto.CompactTextString(m) }
func (*ForwardEventRequest) ProtoMessage()    {}
func (*ForwardEventRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_027b0c31eafcf852, []int{0}
}

func (m *ForwardEventRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ForwardEventRequest.Unmarshal(m, b)
}
func (m *ForwardEventRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ForwardEventRequest.Marshal(b, m, deterministic)
}
func (m *ForwardEventRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ForwardEventRequest.Merge(m, src)
}
func (m *ForwardEventRequest) XXX_Size() int {
	return xxx_messageInfo_ForwardEventRequest.Size(m)
}
func (m *ForwardEventRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ForwardEventRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ForwardEventRequest proto.InternalMessageInfo

func (m *ForwardEventRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ForwardEventRequest) GetType() EventType {
	if m != nil {
		return m.Type
	}
	return EventType_UNDEFINED
}

func (m *ForwardEventRequest) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ForwardEventRequest) GetLevel() EventLevel {
	if m != nil {
		return m.Level
	}
	return EventLevel_INFO
}

func (m *ForwardEventRequest) GetCreatedTs() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedTs
	}
	return nil
}

func (m *ForwardEventRequest) GetSource() *EventSource {
	if m != nil {
		return m.Source
	}
	return nil
}

func (m *ForwardEventRequest) GetProcessors() []*ProcessInfo {
	if m != nil {
		return m.Processors
	}
	return nil
}

func (m *ForwardEventRequest) GetData() *EventData {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *ForwardEventRequest) GetCodename() string {
	if m != nil {
		return m.Codename
	}
	return ""
}

func (m *ForwardEventRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *ForwardEventRequest) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func init() {
	proto.RegisterType((*ForwardEventRequest)(nil), "luids.event.v1.ForwardEventRequest")
}

func init() { proto.RegisterFile("forward.proto", fileDescriptor_027b0c31eafcf852) }

var fileDescriptor_027b0c31eafcf852 = []byte{
	// 427 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0xcf, 0x8e, 0xd3, 0x30,
	0x10, 0xc6, 0x49, 0xff, 0xed, 0xd6, 0x85, 0x1e, 0x8c, 0x84, 0x4c, 0xb8, 0x44, 0x8b, 0x10, 0xb9,
	0xac, 0x0d, 0xed, 0x09, 0xed, 0x0d, 0xb1, 0x48, 0x48, 0x20, 0x21, 0xd3, 0x03, 0xe2, 0x82, 0x5c,
	0x67, 0x9a, 0xb5, 0x94, 0x64, 0x8c, 0xed, 0x14, 0xf5, 0x0d, 0x79, 0x2c, 0x14, 0xa7, 0x0b, 0x05,
	0x82, 0xf6, 0x12, 0x4d, 0xec, 0xdf, 0x37, 0x33, 0xfe, 0x66, 0xc8, 0x83, 0x1d, 0xba, 0xef, 0xca,
	0x15, 0xdc, 0x3a, 0x0c, 0x48, 0x97, 0x55, 0x6b, 0x0a, 0xcf, 0x61, 0x0f, 0x4d, 0xe0, 0xfb, 0x97,
	0xe9, 0xba, 0x34, 0xe1, 0xa6, 0xdd, 0x72, 0x8d, 0xb5, 0x28, 0xb1, 0x52, 0x4d, 0x29, 0x22, 0xb8,
	0x6d, 0x77, 0xc2, 0x86, 0x83, 0x05, 0x2f, 0xa0, 0xb6, 0xe1, 0xd0, 0x7f, 0xfb, 0x24, 0xe9, 0xd5,
	0xdd, 0xa2, 0x60, 0x6a, 0xf0, 0x41, 0xd5, 0xf6, 0x77, 0x74, 0x14, 0xaf, 0x4e, 0xc4, 0xb1, 0x99,
	0x4b, 0x83, 0x42, 0x59, 0x23, 0xbc, 0xbe, 0x81, 0x5a, 0x79, 0x11, 0x7b, 0x13, 0x1a, 0xeb, 0x1a,
	0x9b, 0x5e, 0x73, 0xf1, 0x63, 0x4c, 0x1e, 0xbe, 0xed, 0xdf, 0x71, 0xdd, 0xdd, 0x4a, 0xf8, 0xd6,
	0x82, 0x0f, 0x74, 0x49, 0x46, 0xa6, 0x60, 0x49, 0x96, 0xe4, 0x73, 0x39, 0x32, 0x05, 0xbd, 0x24,
	0x93, 0xae, 0x3c, 0x1b, 0x65, 0x49, 0xbe, 0x5c, 0x3d, 0xe6, 0x7f, 0x3e, 0x96, 0x47, 0xed, 0xe6,
	0x60, 0x41, 0x46, 0x8c, 0x52, 0x32, 0xd1, 0x58, 0x00, 0x1b, 0x67, 0x49, 0x3e, 0x95, 0x31, 0xa6,
	0x2f, 0xc8, 0xb4, 0x82, 0x3d, 0x54, 0x6c, 0x12, 0x73, 0xa4, 0x83, 0x39, 0xde, 0x77, 0x84, 0xec,
	0x41, 0xfa, 0x8a, 0x10, 0xed, 0x40, 0x05, 0x28, 0xbe, 0x06, 0xcf, 0xa6, 0x59, 0x92, 0x2f, 0x56,
	0x29, 0x2f, 0x11, 0xcb, 0x0a, 0xf8, 0xad, 0x2f, 0x7c, 0x73, 0x6b, 0x83, 0x9c, 0x1f, 0xe9, 0x8d,
	0xa7, 0x6b, 0x32, 0xf3, 0xd8, 0x3a, 0x0d, 0x6c, 0x16, 0x65, 0x4f, 0x06, 0xab, 0x7d, 0x8a, 0x88,
	0x3c, 0xa2, 0xf4, 0x8a, 0x10, 0xeb, 0x50, 0x83, 0xf7, 0xe8, 0x3c, 0x3b, 0xcb, 0xc6, 0x43, 0xc2,
	0x8f, 0x3d, 0xf1, 0xae, 0xd9, 0xa1, 0x3c, 0xc1, 0x3b, 0x87, 0x0a, 0x15, 0x14, 0x3b, 0x8f, 0xf5,
	0x86, 0x1d, 0x7a, 0xa3, 0x82, 0x92, 0x11, 0xa3, 0x29, 0x39, 0xef, 0x5c, 0x69, 0x54, 0x0d, 0x6c,
	0x1e, 0x6d, 0xfe, 0xf5, 0x4f, 0x33, 0xb2, 0x28, 0xc0, 0x6b, 0x67, 0x6c, 0x30, 0xd8, 0x30, 0x12,
	0xaf, 0x4f, 0x8f, 0x3a, 0x7f, 0x83, 0x2a, 0x3d, 0x5b, 0x64, 0xe3, 0x7c, 0x2e, 0x63, 0xbc, 0xfa,
	0x4c, 0xce, 0x8e, 0x93, 0xa4, 0x1f, 0xc8, 0xfd, 0xd3, 0xa1, 0xd2, 0xa7, 0x7f, 0x77, 0x33, 0x30,
	0xf2, 0xf4, 0xd1, 0x3f, 0xce, 0x5e, 0x77, 0x9b, 0x79, 0x71, 0xef, 0xf5, 0xf3, 0x2f, 0xcf, 0xfe,
	0xb7, 0x5a, 0xfd, 0x4a, 0x95, 0xce, 0x6a, 0x61, 0xb7, 0xdb, 0x59, 0x94, 0xae, 0x7f, 0x06, 0x00,
	0x00, 0xff, 0xff, 0x92, 0xe6, 0xbd, 0x0e, 0x1b, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ForwardClient is the client API for Forward service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ForwardClient interface {
	ForwardEvent(ctx context.Context, in *ForwardEventRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type forwardClient struct {
	cc *grpc.ClientConn
}

func NewForwardClient(cc *grpc.ClientConn) ForwardClient {
	return &forwardClient{cc}
}

func (c *forwardClient) ForwardEvent(ctx context.Context, in *ForwardEventRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/luids.event.v1.Forward/ForwardEvent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ForwardServer is the server API for Forward service.
type ForwardServer interface {
	ForwardEvent(context.Context, *ForwardEventRequest) (*empty.Empty, error)
}

// UnimplementedForwardServer can be embedded to have forward compatible implementations.
type UnimplementedForwardServer struct {
}

func (*UnimplementedForwardServer) ForwardEvent(ctx context.Context, req *ForwardEventRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ForwardEvent not implemented")
}

func RegisterForwardServer(s *grpc.Server, srv ForwardServer) {
	s.RegisterService(&_Forward_serviceDesc, srv)
}

func _Forward_ForwardEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForwardEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForwardServer).ForwardEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/luids.event.v1.Forward/ForwardEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForwardServer).ForwardEvent(ctx, req.(*ForwardEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Forward_serviceDesc = grpc.ServiceDesc{
	ServiceName: "luids.event.v1.Forward",
	HandlerType: (*ForwardServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ForwardEvent",
			Handler:    _Forward_ForwardEvent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "forward.proto",
}
