// Code generated by protoc-gen-go. DO NOT EDIT.
// source: notify.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NotifyEventRequest struct {
	Code                 int32                `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Level                EventLevel           `protobuf:"varint,2,opt,name=level,proto3,enum=luids.event.v1.EventLevel" json:"level,omitempty"`
	CreatedTs            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=created_ts,json=createdTs,proto3" json:"created_ts,omitempty"`
	Source               *EventSource         `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	Data                 *EventData           `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *NotifyEventRequest) Reset()         { *m = NotifyEventRequest{} }
func (m *NotifyEventRequest) String() string { return proto.CompactTextString(m) }
func (*NotifyEventRequest) ProtoMessage()    {}
func (*NotifyEventRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_aba76cc4ebe272d4, []int{0}
}

func (m *NotifyEventRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyEventRequest.Unmarshal(m, b)
}
func (m *NotifyEventRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyEventRequest.Marshal(b, m, deterministic)
}
func (m *NotifyEventRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyEventRequest.Merge(m, src)
}
func (m *NotifyEventRequest) XXX_Size() int {
	return xxx_messageInfo_NotifyEventRequest.Size(m)
}
func (m *NotifyEventRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyEventRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyEventRequest proto.InternalMessageInfo

func (m *NotifyEventRequest) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *NotifyEventRequest) GetLevel() EventLevel {
	if m != nil {
		return m.Level
	}
	return EventLevel_INFO
}

func (m *NotifyEventRequest) GetCreatedTs() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedTs
	}
	return nil
}

func (m *NotifyEventRequest) GetSource() *EventSource {
	if m != nil {
		return m.Source
	}
	return nil
}

func (m *NotifyEventRequest) GetData() *EventData {
	if m != nil {
		return m.Data
	}
	return nil
}

type NotifyEventResponse struct {
	EventID              string   `protobuf:"bytes,1,opt,name=eventID,proto3" json:"eventID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotifyEventResponse) Reset()         { *m = NotifyEventResponse{} }
func (m *NotifyEventResponse) String() string { return proto.CompactTextString(m) }
func (*NotifyEventResponse) ProtoMessage()    {}
func (*NotifyEventResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_aba76cc4ebe272d4, []int{1}
}

func (m *NotifyEventResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyEventResponse.Unmarshal(m, b)
}
func (m *NotifyEventResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyEventResponse.Marshal(b, m, deterministic)
}
func (m *NotifyEventResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyEventResponse.Merge(m, src)
}
func (m *NotifyEventResponse) XXX_Size() int {
	return xxx_messageInfo_NotifyEventResponse.Size(m)
}
func (m *NotifyEventResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyEventResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyEventResponse proto.InternalMessageInfo

func (m *NotifyEventResponse) GetEventID() string {
	if m != nil {
		return m.EventID
	}
	return ""
}

func init() {
	proto.RegisterType((*NotifyEventRequest)(nil), "luids.event.v1.NotifyEventRequest")
	proto.RegisterType((*NotifyEventResponse)(nil), "luids.event.v1.NotifyEventResponse")
}

func init() { proto.RegisterFile("notify.proto", fileDescriptor_aba76cc4ebe272d4) }

var fileDescriptor_aba76cc4ebe272d4 = []byte{
	// 335 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0xc1, 0x4f, 0xc2, 0x30,
	0x14, 0xc6, 0x9d, 0x02, 0x86, 0x62, 0x38, 0xd4, 0xcb, 0x9c, 0x17, 0x32, 0x63, 0xe4, 0x42, 0xab,
	0xe3, 0x64, 0xbc, 0x19, 0x3c, 0x98, 0x18, 0x0f, 0x95, 0x83, 0xf1, 0x62, 0xba, 0xee, 0x31, 0x96,
	0x6c, 0x6b, 0x5d, 0x3b, 0x12, 0xfe, 0x74, 0x6f, 0x86, 0x37, 0x88, 0xa0, 0xe8, 0xad, 0xcb, 0x7e,
	0xbf, 0xf7, 0xf5, 0xeb, 0x23, 0x27, 0xa5, 0x76, 0xd9, 0x6c, 0xc9, 0x4c, 0xa5, 0x9d, 0xa6, 0xfd,
	0xbc, 0xce, 0x12, 0xcb, 0x60, 0x01, 0xa5, 0x63, 0x8b, 0x9b, 0xe0, 0x2e, 0xcd, 0xdc, 0xbc, 0x8e,
	0x99, 0xd2, 0x05, 0x4f, 0x75, 0x2e, 0xcb, 0x94, 0x23, 0x18, 0xd7, 0x33, 0x6e, 0xdc, 0xd2, 0x80,
	0xe5, 0x2e, 0x2b, 0xc0, 0x3a, 0x59, 0x98, 0xef, 0x53, 0x33, 0x2c, 0x88, 0xb6, 0x64, 0x9c, 0x3b,
	0xca, 0x34, 0x97, 0x26, 0xe3, 0x56, 0xcd, 0xa1, 0x90, 0x96, 0x63, 0x0c, 0x57, 0xba, 0x28, 0x74,
	0xd9, 0x38, 0xe1, 0xa7, 0x47, 0xe8, 0x33, 0xde, 0xe8, 0x61, 0xf5, 0x53, 0xc0, 0x47, 0x0d, 0xd6,
	0x51, 0x4a, 0x5a, 0x4a, 0x27, 0xe0, 0x7b, 0x03, 0x6f, 0xd8, 0x16, 0x78, 0xa6, 0xd7, 0xa4, 0x9d,
	0xc3, 0x02, 0x72, 0xff, 0x70, 0xe0, 0x0d, 0xfb, 0x51, 0xc0, 0x76, 0xef, 0xce, 0x70, 0xc0, 0xd3,
	0x8a, 0x10, 0x0d, 0x48, 0x6f, 0x09, 0x51, 0x15, 0x48, 0x07, 0xc9, 0xbb, 0xb3, 0xfe, 0xd1, 0xc0,
	0x1b, 0xf6, 0xa2, 0x80, 0xa5, 0x5a, 0xa7, 0x39, 0xb0, 0x4d, 0x2f, 0x36, 0xdd, 0xd4, 0x10, 0xdd,
	0x35, 0x3d, 0xb5, 0x74, 0x4c, 0x3a, 0x56, 0xd7, 0x95, 0x02, 0xbf, 0x85, 0xda, 0xf9, 0xde, 0xb4,
	0x17, 0x44, 0xc4, 0x1a, 0xa5, 0x23, 0xd2, 0x4a, 0xa4, 0x93, 0x7e, 0x1b, 0x95, 0xb3, 0xbd, 0xca,
	0x44, 0x3a, 0x29, 0x10, 0x0b, 0x39, 0x39, 0xdd, 0xa9, 0x6e, 0x8d, 0x2e, 0x2d, 0x50, 0x9f, 0x1c,
	0xa3, 0xf2, 0x38, 0xc1, 0xfa, 0x5d, 0xb1, 0xf9, 0x8c, 0x62, 0xd2, 0x69, 0x04, 0xfa, 0x4a, 0x7a,
	0x5b, 0x2a, 0x0d, 0x7f, 0x46, 0xfd, 0x7e, 0xd2, 0xe0, 0xe2, 0x5f, 0xa6, 0xc9, 0x0e, 0x0f, 0xee,
	0xaf, 0xde, 0x2e, 0xff, 0x5a, 0x63, 0xb3, 0xbe, 0xb4, 0x32, 0x8a, 0x9b, 0x38, 0xee, 0xe0, 0x03,
	0x8e, 0xbf, 0x02, 0x00, 0x00, 0xff, 0xff, 0xf2, 0x43, 0xe9, 0xbb, 0x51, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// NotifyClient is the client API for Notify service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NotifyClient interface {
	NotifyEvent(ctx context.Context, in *NotifyEventRequest, opts ...grpc.CallOption) (*NotifyEventResponse, error)
}

type notifyClient struct {
	cc *grpc.ClientConn
}

func NewNotifyClient(cc *grpc.ClientConn) NotifyClient {
	return &notifyClient{cc}
}

func (c *notifyClient) NotifyEvent(ctx context.Context, in *NotifyEventRequest, opts ...grpc.CallOption) (*NotifyEventResponse, error) {
	out := new(NotifyEventResponse)
	err := c.cc.Invoke(ctx, "/luids.event.v1.Notify/NotifyEvent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NotifyServer is the server API for Notify service.
type NotifyServer interface {
	NotifyEvent(context.Context, *NotifyEventRequest) (*NotifyEventResponse, error)
}

// UnimplementedNotifyServer can be embedded to have forward compatible implementations.
type UnimplementedNotifyServer struct {
}

func (*UnimplementedNotifyServer) NotifyEvent(ctx context.Context, req *NotifyEventRequest) (*NotifyEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NotifyEvent not implemented")
}

func RegisterNotifyServer(s *grpc.Server, srv NotifyServer) {
	s.RegisterService(&_Notify_serviceDesc, srv)
}

func _Notify_NotifyEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotifyEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifyServer).NotifyEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/luids.event.v1.Notify/NotifyEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifyServer).NotifyEvent(ctx, req.(*NotifyEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Notify_serviceDesc = grpc.ServiceDesc{
	ServiceName: "luids.event.v1.Notify",
	HandlerType: (*NotifyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NotifyEvent",
			Handler:    _Notify_NotifyEvent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "notify.proto",
}
