// Code generated by protoc-gen-go. DO NOT EDIT.
// source: packetproc.proto

package packetprocpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SendPacketRequest struct {
	Metadata             *PacketMetadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Data                 []byte          `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *SendPacketRequest) Reset()         { *m = SendPacketRequest{} }
func (m *SendPacketRequest) String() string { return proto.CompactTextString(m) }
func (*SendPacketRequest) ProtoMessage()    {}
func (*SendPacketRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f96dc3c1506c0ffb, []int{0}
}

func (m *SendPacketRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendPacketRequest.Unmarshal(m, b)
}
func (m *SendPacketRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendPacketRequest.Marshal(b, m, deterministic)
}
func (m *SendPacketRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendPacketRequest.Merge(m, src)
}
func (m *SendPacketRequest) XXX_Size() int {
	return xxx_messageInfo_SendPacketRequest.Size(m)
}
func (m *SendPacketRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendPacketRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendPacketRequest proto.InternalMessageInfo

func (m *SendPacketRequest) GetMetadata() *PacketMetadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *SendPacketRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type PacketMetadata struct {
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	CaptureLength        int32                `protobuf:"varint,2,opt,name=capture_length,json=captureLength,proto3" json:"capture_length,omitempty"`
	Length               int32                `protobuf:"varint,3,opt,name=length,proto3" json:"length,omitempty"`
	InterfaceIndex       int32                `protobuf:"varint,4,opt,name=interface_index,json=interfaceIndex,proto3" json:"interface_index,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *PacketMetadata) Reset()         { *m = PacketMetadata{} }
func (m *PacketMetadata) String() string { return proto.CompactTextString(m) }
func (*PacketMetadata) ProtoMessage()    {}
func (*PacketMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_f96dc3c1506c0ffb, []int{1}
}

func (m *PacketMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PacketMetadata.Unmarshal(m, b)
}
func (m *PacketMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PacketMetadata.Marshal(b, m, deterministic)
}
func (m *PacketMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PacketMetadata.Merge(m, src)
}
func (m *PacketMetadata) XXX_Size() int {
	return xxx_messageInfo_PacketMetadata.Size(m)
}
func (m *PacketMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_PacketMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_PacketMetadata proto.InternalMessageInfo

func (m *PacketMetadata) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *PacketMetadata) GetCaptureLength() int32 {
	if m != nil {
		return m.CaptureLength
	}
	return 0
}

func (m *PacketMetadata) GetLength() int32 {
	if m != nil {
		return m.Length
	}
	return 0
}

func (m *PacketMetadata) GetInterfaceIndex() int32 {
	if m != nil {
		return m.InterfaceIndex
	}
	return 0
}

func init() {
	proto.RegisterType((*SendPacketRequest)(nil), "luids.packetproc.v1.SendPacketRequest")
	proto.RegisterType((*PacketMetadata)(nil), "luids.packetproc.v1.PacketMetadata")
}

func init() { proto.RegisterFile("packetproc.proto", fileDescriptor_f96dc3c1506c0ffb) }

var fileDescriptor_f96dc3c1506c0ffb = []byte{
	// 364 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x52, 0x4d, 0x4b, 0xeb, 0x40,
	0x14, 0x7d, 0xe9, 0xeb, 0xeb, 0x7b, 0x6f, 0xd4, 0xb6, 0x8e, 0x50, 0x4a, 0x56, 0xa5, 0xa2, 0x76,
	0xd3, 0x09, 0xb6, 0x22, 0x82, 0x0b, 0x51, 0xe8, 0xa2, 0xa0, 0x50, 0xe2, 0xc7, 0xc2, 0x4d, 0x99,
	0x24, 0xb7, 0x49, 0x30, 0xc9, 0x8c, 0xc9, 0x4d, 0xb1, 0xfe, 0x09, 0xff, 0x8b, 0xbf, 0x50, 0x32,
	0x49, 0x3f, 0xa4, 0x05, 0x37, 0xba, 0x09, 0x37, 0xe7, 0x9e, 0x73, 0xee, 0xc7, 0x5c, 0x52, 0x97,
	0xdc, 0x7e, 0x02, 0x94, 0xb1, 0xb0, 0x99, 0x8c, 0x05, 0x0a, 0xba, 0x17, 0xa4, 0xbe, 0x93, 0xb0,
	0x15, 0x7c, 0x7a, 0xac, 0xf7, 0x5d, 0x1f, 0xbd, 0xd4, 0x62, 0xb6, 0x08, 0x0d, 0x57, 0x04, 0x3c,
	0x72, 0x0d, 0xc5, 0xb6, 0xd2, 0x89, 0x21, 0x71, 0x26, 0x21, 0x31, 0x20, 0x94, 0x38, 0xcb, 0xbf,
	0xb9, 0x93, 0x7e, 0xfe, 0xb5, 0x08, 0xfd, 0x10, 0x12, 0xe4, 0xa1, 0x5c, 0x46, 0xb9, 0xb8, 0xed,
	0x91, 0xdd, 0x5b, 0x88, 0x9c, 0x91, 0x6a, 0xc3, 0x84, 0xe7, 0x14, 0x12, 0xa4, 0x17, 0xe4, 0x5f,
	0x08, 0xc8, 0x1d, 0x8e, 0xbc, 0xa9, 0xb5, 0xb4, 0xce, 0x56, 0x6f, 0x9f, 0x6d, 0x68, 0x97, 0xe5,
	0xaa, 0x9b, 0x82, 0x6a, 0x2e, 0x44, 0x94, 0x92, 0xb2, 0x12, 0x97, 0x5a, 0x5a, 0x67, 0xdb, 0x54,
	0x71, 0xfb, 0x5d, 0x23, 0xd5, 0xcf, 0x02, 0x7a, 0x46, 0xfe, 0x2f, 0xfa, 0x29, 0x0a, 0xe9, 0xcc,
	0x15, 0xc2, 0x0d, 0x80, 0xcd, 0x47, 0x60, 0x77, 0x73, 0x86, 0xb9, 0x24, 0xd3, 0x03, 0x52, 0xb5,
	0xb9, 0xc4, 0x34, 0x86, 0x71, 0x00, 0x91, 0x8b, 0x9e, 0x2a, 0xf5, 0xc7, 0xdc, 0x29, 0xd0, 0x6b,
	0x05, 0xd2, 0x06, 0xa9, 0x14, 0xe9, 0xdf, 0x2a, 0x5d, 0xfc, 0xd1, 0x23, 0x52, 0xf3, 0x23, 0x84,
	0x78, 0xc2, 0x6d, 0x18, 0xfb, 0x91, 0x03, 0x2f, 0xcd, 0xb2, 0x22, 0x54, 0x17, 0xf0, 0x30, 0x43,
	0x7b, 0x6f, 0x25, 0xf2, 0xf7, 0x32, 0xe2, 0xc1, 0xec, 0x15, 0xe8, 0x03, 0xa9, 0x67, 0xab, 0x1a,
	0xa0, 0x07, 0x71, 0x3e, 0x48, 0x42, 0x0f, 0x37, 0xee, 0x65, 0x6d, 0xa3, 0x7a, 0x63, 0x6d, 0xac,
	0x41, 0xf6, 0x82, 0xed, 0x5f, 0x1d, 0x8d, 0xde, 0x93, 0x5a, 0x26, 0x18, 0x8e, 0xa6, 0x27, 0x3f,
	0x63, 0x7b, 0xfa, 0x8d, 0xb6, 0x57, 0xc6, 0x63, 0x77, 0xe5, 0xde, 0x94, 0x5f, 0xd7, 0x17, 0x06,
	0x97, 0x7e, 0x7e, 0x75, 0x2e, 0x44, 0xc6, 0xd2, 0x5f, 0x5a, 0x56, 0x45, 0xc1, 0xfd, 0x8f, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xd5, 0xe1, 0x67, 0x25, 0x03, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AnalyzeClient is the client API for Analyze service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AnalyzeClient interface {
	SendEtherPackets(ctx context.Context, opts ...grpc.CallOption) (Analyze_SendEtherPacketsClient, error)
	SendIPv4Packets(ctx context.Context, opts ...grpc.CallOption) (Analyze_SendIPv4PacketsClient, error)
	SendIPv6Packets(ctx context.Context, opts ...grpc.CallOption) (Analyze_SendIPv6PacketsClient, error)
}

type analyzeClient struct {
	cc *grpc.ClientConn
}

func NewAnalyzeClient(cc *grpc.ClientConn) AnalyzeClient {
	return &analyzeClient{cc}
}

func (c *analyzeClient) SendEtherPackets(ctx context.Context, opts ...grpc.CallOption) (Analyze_SendEtherPacketsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Analyze_serviceDesc.Streams[0], "/luids.packetproc.v1.Analyze/SendEtherPackets", opts...)
	if err != nil {
		return nil, err
	}
	x := &analyzeSendEtherPacketsClient{stream}
	return x, nil
}

type Analyze_SendEtherPacketsClient interface {
	Send(*SendPacketRequest) error
	CloseAndRecv() (*empty.Empty, error)
	grpc.ClientStream
}

type analyzeSendEtherPacketsClient struct {
	grpc.ClientStream
}

func (x *analyzeSendEtherPacketsClient) Send(m *SendPacketRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *analyzeSendEtherPacketsClient) CloseAndRecv() (*empty.Empty, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(empty.Empty)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *analyzeClient) SendIPv4Packets(ctx context.Context, opts ...grpc.CallOption) (Analyze_SendIPv4PacketsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Analyze_serviceDesc.Streams[1], "/luids.packetproc.v1.Analyze/SendIPv4Packets", opts...)
	if err != nil {
		return nil, err
	}
	x := &analyzeSendIPv4PacketsClient{stream}
	return x, nil
}

type Analyze_SendIPv4PacketsClient interface {
	Send(*SendPacketRequest) error
	CloseAndRecv() (*empty.Empty, error)
	grpc.ClientStream
}

type analyzeSendIPv4PacketsClient struct {
	grpc.ClientStream
}

func (x *analyzeSendIPv4PacketsClient) Send(m *SendPacketRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *analyzeSendIPv4PacketsClient) CloseAndRecv() (*empty.Empty, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(empty.Empty)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *analyzeClient) SendIPv6Packets(ctx context.Context, opts ...grpc.CallOption) (Analyze_SendIPv6PacketsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Analyze_serviceDesc.Streams[2], "/luids.packetproc.v1.Analyze/SendIPv6Packets", opts...)
	if err != nil {
		return nil, err
	}
	x := &analyzeSendIPv6PacketsClient{stream}
	return x, nil
}

type Analyze_SendIPv6PacketsClient interface {
	Send(*SendPacketRequest) error
	CloseAndRecv() (*empty.Empty, error)
	grpc.ClientStream
}

type analyzeSendIPv6PacketsClient struct {
	grpc.ClientStream
}

func (x *analyzeSendIPv6PacketsClient) Send(m *SendPacketRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *analyzeSendIPv6PacketsClient) CloseAndRecv() (*empty.Empty, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(empty.Empty)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// AnalyzeServer is the server API for Analyze service.
type AnalyzeServer interface {
	SendEtherPackets(Analyze_SendEtherPacketsServer) error
	SendIPv4Packets(Analyze_SendIPv4PacketsServer) error
	SendIPv6Packets(Analyze_SendIPv6PacketsServer) error
}

// UnimplementedAnalyzeServer can be embedded to have forward compatible implementations.
type UnimplementedAnalyzeServer struct {
}

func (*UnimplementedAnalyzeServer) SendEtherPackets(srv Analyze_SendEtherPacketsServer) error {
	return status.Errorf(codes.Unimplemented, "method SendEtherPackets not implemented")
}
func (*UnimplementedAnalyzeServer) SendIPv4Packets(srv Analyze_SendIPv4PacketsServer) error {
	return status.Errorf(codes.Unimplemented, "method SendIPv4Packets not implemented")
}
func (*UnimplementedAnalyzeServer) SendIPv6Packets(srv Analyze_SendIPv6PacketsServer) error {
	return status.Errorf(codes.Unimplemented, "method SendIPv6Packets not implemented")
}

func RegisterAnalyzeServer(s *grpc.Server, srv AnalyzeServer) {
	s.RegisterService(&_Analyze_serviceDesc, srv)
}

func _Analyze_SendEtherPackets_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AnalyzeServer).SendEtherPackets(&analyzeSendEtherPacketsServer{stream})
}

type Analyze_SendEtherPacketsServer interface {
	SendAndClose(*empty.Empty) error
	Recv() (*SendPacketRequest, error)
	grpc.ServerStream
}

type analyzeSendEtherPacketsServer struct {
	grpc.ServerStream
}

func (x *analyzeSendEtherPacketsServer) SendAndClose(m *empty.Empty) error {
	return x.ServerStream.SendMsg(m)
}

func (x *analyzeSendEtherPacketsServer) Recv() (*SendPacketRequest, error) {
	m := new(SendPacketRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Analyze_SendIPv4Packets_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AnalyzeServer).SendIPv4Packets(&analyzeSendIPv4PacketsServer{stream})
}

type Analyze_SendIPv4PacketsServer interface {
	SendAndClose(*empty.Empty) error
	Recv() (*SendPacketRequest, error)
	grpc.ServerStream
}

type analyzeSendIPv4PacketsServer struct {
	grpc.ServerStream
}

func (x *analyzeSendIPv4PacketsServer) SendAndClose(m *empty.Empty) error {
	return x.ServerStream.SendMsg(m)
}

func (x *analyzeSendIPv4PacketsServer) Recv() (*SendPacketRequest, error) {
	m := new(SendPacketRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Analyze_SendIPv6Packets_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AnalyzeServer).SendIPv6Packets(&analyzeSendIPv6PacketsServer{stream})
}

type Analyze_SendIPv6PacketsServer interface {
	SendAndClose(*empty.Empty) error
	Recv() (*SendPacketRequest, error)
	grpc.ServerStream
}

type analyzeSendIPv6PacketsServer struct {
	grpc.ServerStream
}

func (x *analyzeSendIPv6PacketsServer) SendAndClose(m *empty.Empty) error {
	return x.ServerStream.SendMsg(m)
}

func (x *analyzeSendIPv6PacketsServer) Recv() (*SendPacketRequest, error) {
	m := new(SendPacketRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Analyze_serviceDesc = grpc.ServiceDesc{
	ServiceName: "luids.packetproc.v1.Analyze",
	HandlerType: (*AnalyzeServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SendEtherPackets",
			Handler:       _Analyze_SendEtherPackets_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "SendIPv4Packets",
			Handler:       _Analyze_SendIPv4Packets_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "SendIPv6Packets",
			Handler:       _Analyze_SendIPv6Packets_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "packetproc.proto",
}
