// Code generated by protoc-gen-go. DO NOT EDIT.
// source: packetproc.proto

package packetprocpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SendPacketRequest struct {
	Metadata             *PacketMetadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Data                 []byte          `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *SendPacketRequest) Reset()         { *m = SendPacketRequest{} }
func (m *SendPacketRequest) String() string { return proto.CompactTextString(m) }
func (*SendPacketRequest) ProtoMessage()    {}
func (*SendPacketRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f96dc3c1506c0ffb, []int{0}
}

func (m *SendPacketRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendPacketRequest.Unmarshal(m, b)
}
func (m *SendPacketRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendPacketRequest.Marshal(b, m, deterministic)
}
func (m *SendPacketRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendPacketRequest.Merge(m, src)
}
func (m *SendPacketRequest) XXX_Size() int {
	return xxx_messageInfo_SendPacketRequest.Size(m)
}
func (m *SendPacketRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendPacketRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendPacketRequest proto.InternalMessageInfo

func (m *SendPacketRequest) GetMetadata() *PacketMetadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *SendPacketRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type PacketMetadata struct {
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	CaptureLength        int32                `protobuf:"varint,2,opt,name=capture_length,json=captureLength,proto3" json:"capture_length,omitempty"`
	Length               int32                `protobuf:"varint,3,opt,name=length,proto3" json:"length,omitempty"`
	InterfaceIndex       int32                `protobuf:"varint,4,opt,name=interface_index,json=interfaceIndex,proto3" json:"interface_index,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *PacketMetadata) Reset()         { *m = PacketMetadata{} }
func (m *PacketMetadata) String() string { return proto.CompactTextString(m) }
func (*PacketMetadata) ProtoMessage()    {}
func (*PacketMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_f96dc3c1506c0ffb, []int{1}
}

func (m *PacketMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PacketMetadata.Unmarshal(m, b)
}
func (m *PacketMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PacketMetadata.Marshal(b, m, deterministic)
}
func (m *PacketMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PacketMetadata.Merge(m, src)
}
func (m *PacketMetadata) XXX_Size() int {
	return xxx_messageInfo_PacketMetadata.Size(m)
}
func (m *PacketMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_PacketMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_PacketMetadata proto.InternalMessageInfo

func (m *PacketMetadata) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *PacketMetadata) GetCaptureLength() int32 {
	if m != nil {
		return m.CaptureLength
	}
	return 0
}

func (m *PacketMetadata) GetLength() int32 {
	if m != nil {
		return m.Length
	}
	return 0
}

func (m *PacketMetadata) GetInterfaceIndex() int32 {
	if m != nil {
		return m.InterfaceIndex
	}
	return 0
}

func init() {
	proto.RegisterType((*SendPacketRequest)(nil), "luids.packetproc.v1.SendPacketRequest")
	proto.RegisterType((*PacketMetadata)(nil), "luids.packetproc.v1.PacketMetadata")
}

func init() { proto.RegisterFile("packetproc.proto", fileDescriptor_f96dc3c1506c0ffb) }

var fileDescriptor_f96dc3c1506c0ffb = []byte{
	// 340 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x51, 0x4d, 0x4b, 0xeb, 0x40,
	0x14, 0x7d, 0x79, 0xaf, 0xaf, 0xea, 0xa8, 0xb5, 0x8e, 0x50, 0x4a, 0x56, 0xa5, 0xa2, 0x76, 0xd3,
	0x09, 0xb6, 0x1b, 0xc1, 0x85, 0x28, 0x74, 0x21, 0x28, 0x48, 0x14, 0x17, 0x6e, 0xca, 0x24, 0xb9,
	0x9d, 0x0c, 0x26, 0x33, 0x63, 0x72, 0x23, 0xd6, 0x9f, 0xe5, 0x2f, 0x94, 0x4e, 0xd2, 0x0f, 0x69,
	0xc1, 0xcd, 0x70, 0xe7, 0xdc, 0x73, 0xee, 0xd7, 0x21, 0x4d, 0xc3, 0xc3, 0x57, 0x40, 0x93, 0xe9,
	0x90, 0x99, 0x4c, 0xa3, 0xa6, 0x47, 0x49, 0x21, 0xa3, 0x9c, 0xad, 0xe0, 0xef, 0xe7, 0xee, 0x50,
	0x48, 0x8c, 0x8b, 0x80, 0x85, 0x3a, 0xf5, 0x84, 0x4e, 0xb8, 0x12, 0x9e, 0x65, 0x07, 0xc5, 0xc4,
	0x33, 0x38, 0x35, 0x90, 0x7b, 0x90, 0x1a, 0x9c, 0x96, 0x6f, 0x59, 0xc9, 0xbd, 0xfc, 0x5d, 0x84,
	0x32, 0x85, 0x1c, 0x79, 0x6a, 0x96, 0x51, 0x29, 0xee, 0xc6, 0xe4, 0xf0, 0x11, 0x54, 0xf4, 0x60,
	0xc7, 0xf0, 0xe1, 0xad, 0x80, 0x1c, 0xe9, 0x15, 0xd9, 0x4e, 0x01, 0x79, 0xc4, 0x91, 0xb7, 0x9d,
	0x8e, 0xd3, 0xdb, 0x1d, 0x1c, 0xb3, 0x0d, 0xe3, 0xb2, 0x52, 0x75, 0x5f, 0x51, 0xfd, 0x85, 0x88,
	0x52, 0x52, 0xb3, 0xe2, 0xbf, 0x1d, 0xa7, 0xb7, 0xe7, 0xdb, 0xb8, 0xfb, 0xe5, 0x90, 0xc6, 0x4f,
	0x01, 0xbd, 0x20, 0x3b, 0x8b, 0x79, 0xaa, 0x46, 0x2e, 0x13, 0x5a, 0x8b, 0x04, 0xd8, 0x7c, 0x05,
	0xf6, 0x34, 0x67, 0xf8, 0x4b, 0x32, 0x3d, 0x21, 0x8d, 0x90, 0x1b, 0x2c, 0x32, 0x18, 0x27, 0xa0,
	0x04, 0xc6, 0xb6, 0xd5, 0x7f, 0x7f, 0xbf, 0x42, 0xef, 0x2c, 0x48, 0x5b, 0xa4, 0x5e, 0xa5, 0xff,
	0xd9, 0x74, 0xf5, 0xa3, 0x67, 0xe4, 0x40, 0x2a, 0x84, 0x6c, 0xc2, 0x43, 0x18, 0x4b, 0x15, 0xc1,
	0x47, 0xbb, 0x66, 0x09, 0x8d, 0x05, 0x7c, 0x3b, 0x43, 0x07, 0x9c, 0x6c, 0x5d, 0x2b, 0x9e, 0x4c,
	0x3f, 0x81, 0x3e, 0x93, 0xe6, 0xec, 0x52, 0x23, 0x8c, 0x21, 0x2b, 0xf7, 0xc8, 0xe9, 0xe9, 0xc6,
	0xb3, 0xac, 0x1d, 0xd4, 0x6d, 0xad, 0x6d, 0x35, 0x9a, 0x19, 0xd8, 0xfd, 0xd3, 0x73, 0x6e, 0xbc,
	0x97, 0xfe, 0x8a, 0x81, 0xb6, 0x5e, 0x5f, 0x6a, 0x8f, 0x1b, 0x59, 0xda, 0x28, 0x40, 0x79, 0xcb,
	0xfa, 0x26, 0x08, 0xea, 0x16, 0x1e, 0x7e, 0x07, 0x00, 0x00, 0xff, 0xff, 0xce, 0xe5, 0xd4, 0x9b,
	0x54, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AnalyzeClient is the client API for Analyze service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AnalyzeClient interface {
	SendEtherPackets(ctx context.Context, opts ...grpc.CallOption) (Analyze_SendEtherPacketsClient, error)
}

type analyzeClient struct {
	cc *grpc.ClientConn
}

func NewAnalyzeClient(cc *grpc.ClientConn) AnalyzeClient {
	return &analyzeClient{cc}
}

func (c *analyzeClient) SendEtherPackets(ctx context.Context, opts ...grpc.CallOption) (Analyze_SendEtherPacketsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Analyze_serviceDesc.Streams[0], "/luids.packetproc.v1.Analyze/SendEtherPackets", opts...)
	if err != nil {
		return nil, err
	}
	x := &analyzeSendEtherPacketsClient{stream}
	return x, nil
}

type Analyze_SendEtherPacketsClient interface {
	Send(*SendPacketRequest) error
	CloseAndRecv() (*empty.Empty, error)
	grpc.ClientStream
}

type analyzeSendEtherPacketsClient struct {
	grpc.ClientStream
}

func (x *analyzeSendEtherPacketsClient) Send(m *SendPacketRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *analyzeSendEtherPacketsClient) CloseAndRecv() (*empty.Empty, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(empty.Empty)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// AnalyzeServer is the server API for Analyze service.
type AnalyzeServer interface {
	SendEtherPackets(Analyze_SendEtherPacketsServer) error
}

// UnimplementedAnalyzeServer can be embedded to have forward compatible implementations.
type UnimplementedAnalyzeServer struct {
}

func (*UnimplementedAnalyzeServer) SendEtherPackets(srv Analyze_SendEtherPacketsServer) error {
	return status.Errorf(codes.Unimplemented, "method SendEtherPackets not implemented")
}

func RegisterAnalyzeServer(s *grpc.Server, srv AnalyzeServer) {
	s.RegisterService(&_Analyze_serviceDesc, srv)
}

func _Analyze_SendEtherPackets_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AnalyzeServer).SendEtherPackets(&analyzeSendEtherPacketsServer{stream})
}

type Analyze_SendEtherPacketsServer interface {
	SendAndClose(*empty.Empty) error
	Recv() (*SendPacketRequest, error)
	grpc.ServerStream
}

type analyzeSendEtherPacketsServer struct {
	grpc.ServerStream
}

func (x *analyzeSendEtherPacketsServer) SendAndClose(m *empty.Empty) error {
	return x.ServerStream.SendMsg(m)
}

func (x *analyzeSendEtherPacketsServer) Recv() (*SendPacketRequest, error) {
	m := new(SendPacketRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Analyze_serviceDesc = grpc.ServiceDesc{
	ServiceName: "luids.packetproc.v1.Analyze",
	HandlerType: (*AnalyzeServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SendEtherPackets",
			Handler:       _Analyze_SendEtherPackets_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "packetproc.proto",
}
