// Copyright 2019 Luis Guillén Civera <luisguillenc@gmail.com>. View LICENSE.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.6.1
// source: github.com/luids-io/api/schemas/dnsutil/archive.proto

package pb

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type SaveResolvRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ts             *timestamp.Timestamp             `protobuf:"bytes,1,opt,name=ts,proto3" json:"ts,omitempty"`
	Duration       int64                            `protobuf:"varint,2,opt,name=duration,proto3" json:"duration,omitempty"`
	ServerIp       string                           `protobuf:"bytes,3,opt,name=server_ip,json=serverIp,proto3" json:"server_ip,omitempty"`
	ClientIp       string                           `protobuf:"bytes,4,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	Qid            int32                            `protobuf:"varint,5,opt,name=qid,proto3" json:"qid,omitempty"`
	Name           string                           `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	IsIpv6         bool                             `protobuf:"varint,7,opt,name=is_ipv6,json=isIpv6,proto3" json:"is_ipv6,omitempty"`
	QueryFlags     *SaveResolvRequest_QueryFlags    `protobuf:"bytes,8,opt,name=query_flags,json=queryFlags,proto3" json:"query_flags,omitempty"`
	ReturnCode     int32                            `protobuf:"varint,9,opt,name=return_code,json=returnCode,proto3" json:"return_code,omitempty"`
	ResolvedIps    []string                         `protobuf:"bytes,10,rep,name=resolved_ips,json=resolvedIps,proto3" json:"resolved_ips,omitempty"`
	ResolvedCnames []string                         `protobuf:"bytes,11,rep,name=resolved_cnames,json=resolvedCnames,proto3" json:"resolved_cnames,omitempty"`
	ResponseFlags  *SaveResolvRequest_ResponseFlags `protobuf:"bytes,12,opt,name=response_flags,json=responseFlags,proto3" json:"response_flags,omitempty"`
}

func (x *SaveResolvRequest) Reset() {
	*x = SaveResolvRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_luids_io_api_schemas_dnsutil_archive_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveResolvRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveResolvRequest) ProtoMessage() {}

func (x *SaveResolvRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_luids_io_api_schemas_dnsutil_archive_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveResolvRequest.ProtoReflect.Descriptor instead.
func (*SaveResolvRequest) Descriptor() ([]byte, []int) {
	return file_github_com_luids_io_api_schemas_dnsutil_archive_proto_rawDescGZIP(), []int{0}
}

func (x *SaveResolvRequest) GetTs() *timestamp.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *SaveResolvRequest) GetDuration() int64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *SaveResolvRequest) GetServerIp() string {
	if x != nil {
		return x.ServerIp
	}
	return ""
}

func (x *SaveResolvRequest) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

func (x *SaveResolvRequest) GetQid() int32 {
	if x != nil {
		return x.Qid
	}
	return 0
}

func (x *SaveResolvRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SaveResolvRequest) GetIsIpv6() bool {
	if x != nil {
		return x.IsIpv6
	}
	return false
}

func (x *SaveResolvRequest) GetQueryFlags() *SaveResolvRequest_QueryFlags {
	if x != nil {
		return x.QueryFlags
	}
	return nil
}

func (x *SaveResolvRequest) GetReturnCode() int32 {
	if x != nil {
		return x.ReturnCode
	}
	return 0
}

func (x *SaveResolvRequest) GetResolvedIps() []string {
	if x != nil {
		return x.ResolvedIps
	}
	return nil
}

func (x *SaveResolvRequest) GetResolvedCnames() []string {
	if x != nil {
		return x.ResolvedCnames
	}
	return nil
}

func (x *SaveResolvRequest) GetResponseFlags() *SaveResolvRequest_ResponseFlags {
	if x != nil {
		return x.ResponseFlags
	}
	return nil
}

type SaveResolvResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *SaveResolvResponse) Reset() {
	*x = SaveResolvResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_luids_io_api_schemas_dnsutil_archive_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveResolvResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveResolvResponse) ProtoMessage() {}

func (x *SaveResolvResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_luids_io_api_schemas_dnsutil_archive_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveResolvResponse.ProtoReflect.Descriptor instead.
func (*SaveResolvResponse) Descriptor() ([]byte, []int) {
	return file_github_com_luids_io_api_schemas_dnsutil_archive_proto_rawDescGZIP(), []int{1}
}

func (x *SaveResolvResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type SaveResolvRequest_QueryFlags struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Do                bool `protobuf:"varint,1,opt,name=do,proto3" json:"do,omitempty"`
	AuthenticatedData bool `protobuf:"varint,2,opt,name=authenticated_data,json=authenticatedData,proto3" json:"authenticated_data,omitempty"`
	CheckingDisabled  bool `protobuf:"varint,3,opt,name=checking_disabled,json=checkingDisabled,proto3" json:"checking_disabled,omitempty"`
}

func (x *SaveResolvRequest_QueryFlags) Reset() {
	*x = SaveResolvRequest_QueryFlags{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_luids_io_api_schemas_dnsutil_archive_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveResolvRequest_QueryFlags) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveResolvRequest_QueryFlags) ProtoMessage() {}

func (x *SaveResolvRequest_QueryFlags) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_luids_io_api_schemas_dnsutil_archive_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveResolvRequest_QueryFlags.ProtoReflect.Descriptor instead.
func (*SaveResolvRequest_QueryFlags) Descriptor() ([]byte, []int) {
	return file_github_com_luids_io_api_schemas_dnsutil_archive_proto_rawDescGZIP(), []int{0, 0}
}

func (x *SaveResolvRequest_QueryFlags) GetDo() bool {
	if x != nil {
		return x.Do
	}
	return false
}

func (x *SaveResolvRequest_QueryFlags) GetAuthenticatedData() bool {
	if x != nil {
		return x.AuthenticatedData
	}
	return false
}

func (x *SaveResolvRequest_QueryFlags) GetCheckingDisabled() bool {
	if x != nil {
		return x.CheckingDisabled
	}
	return false
}

type SaveResolvRequest_ResponseFlags struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AuthenticatedData bool `protobuf:"varint,1,opt,name=authenticated_data,json=authenticatedData,proto3" json:"authenticated_data,omitempty"`
}

func (x *SaveResolvRequest_ResponseFlags) Reset() {
	*x = SaveResolvRequest_ResponseFlags{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_luids_io_api_schemas_dnsutil_archive_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveResolvRequest_ResponseFlags) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveResolvRequest_ResponseFlags) ProtoMessage() {}

func (x *SaveResolvRequest_ResponseFlags) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_luids_io_api_schemas_dnsutil_archive_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveResolvRequest_ResponseFlags.ProtoReflect.Descriptor instead.
func (*SaveResolvRequest_ResponseFlags) Descriptor() ([]byte, []int) {
	return file_github_com_luids_io_api_schemas_dnsutil_archive_proto_rawDescGZIP(), []int{0, 1}
}

func (x *SaveResolvRequest_ResponseFlags) GetAuthenticatedData() bool {
	if x != nil {
		return x.AuthenticatedData
	}
	return false
}

var File_github_com_luids_io_api_schemas_dnsutil_archive_proto protoreflect.FileDescriptor

var file_github_com_luids_io_api_schemas_dnsutil_archive_proto_rawDesc = []byte{
	0x0a, 0x35, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x75, 0x69,
	0x64, 0x73, 0x2d, 0x69, 0x6f, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61,
	0x73, 0x2f, 0x64, 0x6e, 0x73, 0x75, 0x74, 0x69, 0x6c, 0x2f, 0x61, 0x72, 0x63, 0x68, 0x69, 0x76,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x6c, 0x75, 0x69, 0x64, 0x73, 0x2e, 0x64,
	0x6e, 0x73, 0x75, 0x74, 0x69, 0x6c, 0x2e, 0x76, 0x31, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa6, 0x05, 0x0a, 0x11, 0x53,
	0x61, 0x76, 0x65, 0x52, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x2a, 0x0a, 0x02, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x02, 0x74, 0x73, 0x12, 0x1a, 0x0a, 0x08,
	0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08,
	0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x5f, 0x69, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x49, 0x70, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f,
	0x69, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x49, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x71, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x03, 0x71, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x69, 0x73, 0x5f, 0x69,
	0x70, 0x76, 0x36, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x69, 0x73, 0x49, 0x70, 0x76,
	0x36, 0x12, 0x4f, 0x0a, 0x0b, 0x71, 0x75, 0x65, 0x72, 0x79, 0x5f, 0x66, 0x6c, 0x61, 0x67, 0x73,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x6c, 0x75, 0x69, 0x64, 0x73, 0x2e, 0x64,
	0x6e, 0x73, 0x75, 0x74, 0x69, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x61, 0x76, 0x65, 0x52, 0x65,
	0x73, 0x6f, 0x6c, 0x76, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x51, 0x75, 0x65, 0x72,
	0x79, 0x46, 0x6c, 0x61, 0x67, 0x73, 0x52, 0x0a, 0x71, 0x75, 0x65, 0x72, 0x79, 0x46, 0x6c, 0x61,
	0x67, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x5f, 0x63, 0x6f, 0x64,
	0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x72, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x43,
	0x6f, 0x64, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x72, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x64, 0x5f,
	0x69, 0x70, 0x73, 0x18, 0x0a, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65, 0x73, 0x6f, 0x6c,
	0x76, 0x65, 0x64, 0x49, 0x70, 0x73, 0x12, 0x27, 0x0a, 0x0f, 0x72, 0x65, 0x73, 0x6f, 0x6c, 0x76,
	0x65, 0x64, 0x5f, 0x63, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x18, 0x0b, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x0e, 0x72, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x64, 0x43, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x12,
	0x58, 0x0a, 0x0e, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x66, 0x6c, 0x61, 0x67,
	0x73, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x31, 0x2e, 0x6c, 0x75, 0x69, 0x64, 0x73, 0x2e,
	0x64, 0x6e, 0x73, 0x75, 0x74, 0x69, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x61, 0x76, 0x65, 0x52,
	0x65, 0x73, 0x6f, 0x6c, 0x76, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x46, 0x6c, 0x61, 0x67, 0x73, 0x52, 0x0d, 0x72, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x46, 0x6c, 0x61, 0x67, 0x73, 0x1a, 0x78, 0x0a, 0x0a, 0x51, 0x75, 0x65,
	0x72, 0x79, 0x46, 0x6c, 0x61, 0x67, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x64, 0x6f, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x02, 0x64, 0x6f, 0x12, 0x2d, 0x0a, 0x12, 0x61, 0x75, 0x74, 0x68, 0x65,
	0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x11, 0x61, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74,
	0x65, 0x64, 0x44, 0x61, 0x74, 0x61, 0x12, 0x2b, 0x0a, 0x11, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x69,
	0x6e, 0x67, 0x5f, 0x64, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x10, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x44, 0x69, 0x73, 0x61, 0x62,
	0x6c, 0x65, 0x64, 0x1a, 0x3e, 0x0a, 0x0d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x46,
	0x6c, 0x61, 0x67, 0x73, 0x12, 0x2d, 0x0a, 0x12, 0x61, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69,
	0x63, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x11, 0x61, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x65, 0x64, 0x44,
	0x61, 0x74, 0x61, 0x22, 0x24, 0x0a, 0x12, 0x53, 0x61, 0x76, 0x65, 0x52, 0x65, 0x73, 0x6f, 0x6c,
	0x76, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x32, 0x64, 0x0a, 0x07, 0x41, 0x72, 0x63,
	0x68, 0x69, 0x76, 0x65, 0x12, 0x59, 0x0a, 0x0a, 0x53, 0x61, 0x76, 0x65, 0x52, 0x65, 0x73, 0x6f,
	0x6c, 0x76, 0x12, 0x23, 0x2e, 0x6c, 0x75, 0x69, 0x64, 0x73, 0x2e, 0x64, 0x6e, 0x73, 0x75, 0x74,
	0x69, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x61, 0x76, 0x65, 0x52, 0x65, 0x73, 0x6f, 0x6c, 0x76,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x6c, 0x75, 0x69, 0x64, 0x73, 0x2e,
	0x64, 0x6e, 0x73, 0x75, 0x74, 0x69, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x61, 0x76, 0x65, 0x52,
	0x65, 0x73, 0x6f, 0x6c, 0x76, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42,
	0x29, 0x5a, 0x27, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x75,
	0x69, 0x64, 0x73, 0x2d, 0x69, 0x6f, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x64, 0x6e, 0x73, 0x75, 0x74,
	0x69, 0x6c, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_github_com_luids_io_api_schemas_dnsutil_archive_proto_rawDescOnce sync.Once
	file_github_com_luids_io_api_schemas_dnsutil_archive_proto_rawDescData = file_github_com_luids_io_api_schemas_dnsutil_archive_proto_rawDesc
)

func file_github_com_luids_io_api_schemas_dnsutil_archive_proto_rawDescGZIP() []byte {
	file_github_com_luids_io_api_schemas_dnsutil_archive_proto_rawDescOnce.Do(func() {
		file_github_com_luids_io_api_schemas_dnsutil_archive_proto_rawDescData = protoimpl.X.CompressGZIP(file_github_com_luids_io_api_schemas_dnsutil_archive_proto_rawDescData)
	})
	return file_github_com_luids_io_api_schemas_dnsutil_archive_proto_rawDescData
}

var file_github_com_luids_io_api_schemas_dnsutil_archive_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_github_com_luids_io_api_schemas_dnsutil_archive_proto_goTypes = []interface{}{
	(*SaveResolvRequest)(nil),               // 0: luids.dnsutil.v1.SaveResolvRequest
	(*SaveResolvResponse)(nil),              // 1: luids.dnsutil.v1.SaveResolvResponse
	(*SaveResolvRequest_QueryFlags)(nil),    // 2: luids.dnsutil.v1.SaveResolvRequest.QueryFlags
	(*SaveResolvRequest_ResponseFlags)(nil), // 3: luids.dnsutil.v1.SaveResolvRequest.ResponseFlags
	(*timestamp.Timestamp)(nil),             // 4: google.protobuf.Timestamp
}
var file_github_com_luids_io_api_schemas_dnsutil_archive_proto_depIdxs = []int32{
	4, // 0: luids.dnsutil.v1.SaveResolvRequest.ts:type_name -> google.protobuf.Timestamp
	2, // 1: luids.dnsutil.v1.SaveResolvRequest.query_flags:type_name -> luids.dnsutil.v1.SaveResolvRequest.QueryFlags
	3, // 2: luids.dnsutil.v1.SaveResolvRequest.response_flags:type_name -> luids.dnsutil.v1.SaveResolvRequest.ResponseFlags
	0, // 3: luids.dnsutil.v1.Archive.SaveResolv:input_type -> luids.dnsutil.v1.SaveResolvRequest
	1, // 4: luids.dnsutil.v1.Archive.SaveResolv:output_type -> luids.dnsutil.v1.SaveResolvResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_github_com_luids_io_api_schemas_dnsutil_archive_proto_init() }
func file_github_com_luids_io_api_schemas_dnsutil_archive_proto_init() {
	if File_github_com_luids_io_api_schemas_dnsutil_archive_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_github_com_luids_io_api_schemas_dnsutil_archive_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveResolvRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_luids_io_api_schemas_dnsutil_archive_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveResolvResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_luids_io_api_schemas_dnsutil_archive_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveResolvRequest_QueryFlags); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_luids_io_api_schemas_dnsutil_archive_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveResolvRequest_ResponseFlags); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_github_com_luids_io_api_schemas_dnsutil_archive_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_github_com_luids_io_api_schemas_dnsutil_archive_proto_goTypes,
		DependencyIndexes: file_github_com_luids_io_api_schemas_dnsutil_archive_proto_depIdxs,
		MessageInfos:      file_github_com_luids_io_api_schemas_dnsutil_archive_proto_msgTypes,
	}.Build()
	File_github_com_luids_io_api_schemas_dnsutil_archive_proto = out.File
	file_github_com_luids_io_api_schemas_dnsutil_archive_proto_rawDesc = nil
	file_github_com_luids_io_api_schemas_dnsutil_archive_proto_goTypes = nil
	file_github_com_luids_io_api_schemas_dnsutil_archive_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ArchiveClient is the client API for Archive service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ArchiveClient interface {
	SaveResolv(ctx context.Context, in *SaveResolvRequest, opts ...grpc.CallOption) (*SaveResolvResponse, error)
}

type archiveClient struct {
	cc grpc.ClientConnInterface
}

func NewArchiveClient(cc grpc.ClientConnInterface) ArchiveClient {
	return &archiveClient{cc}
}

func (c *archiveClient) SaveResolv(ctx context.Context, in *SaveResolvRequest, opts ...grpc.CallOption) (*SaveResolvResponse, error) {
	out := new(SaveResolvResponse)
	err := c.cc.Invoke(ctx, "/luids.dnsutil.v1.Archive/SaveResolv", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ArchiveServer is the server API for Archive service.
type ArchiveServer interface {
	SaveResolv(context.Context, *SaveResolvRequest) (*SaveResolvResponse, error)
}

// UnimplementedArchiveServer can be embedded to have forward compatible implementations.
type UnimplementedArchiveServer struct {
}

func (*UnimplementedArchiveServer) SaveResolv(context.Context, *SaveResolvRequest) (*SaveResolvResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveResolv not implemented")
}

func RegisterArchiveServer(s *grpc.Server, srv ArchiveServer) {
	s.RegisterService(&_Archive_serviceDesc, srv)
}

func _Archive_SaveResolv_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveResolvRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArchiveServer).SaveResolv(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/luids.dnsutil.v1.Archive/SaveResolv",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArchiveServer).SaveResolv(ctx, req.(*SaveResolvRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Archive_serviceDesc = grpc.ServiceDesc{
	ServiceName: "luids.dnsutil.v1.Archive",
	HandlerType: (*ArchiveServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SaveResolv",
			Handler:    _Archive_SaveResolv_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/luids-io/api/schemas/dnsutil/archive.proto",
}
